### ISSUE TITLE
Question - Can the gtk theme apply to  font and font size for user listings and passworrd entry.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/slick-greeter#114]
```
 * slick-greeter version 1.2.2+tara
 * Distribution - Mint 19 Cinnamon
 * Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5
 * 64 bit
 ```

**Issue**

I'm trying to work out if the font-size and font used for the user listing and password entry dialog are themeable via GTK theme. 

I note that a font-name can be set in `/etc/lightdm/slick-greeter.conf` which controls the menubar and menu font.

If it is themeable can anyone point me in the direction of the correct style selector?

**Comment by JosephMcc** [comment]
To find the style classes used you can run `slick-greeter --test-mode` to run in from the terminal. Then you can use GtkInspector on it. The selector for the password entry for example is `entry.lightdm`.

I'm going to close this since it isn't really an issue/bug report. You can still post in it and we get email notifications for it.
