### ISSUE TITLE
The login window on bootup is very small on high-resolution (high-DPI) screens

### ISSUE THREAD

**Issue by marek-lach** [linuxmint/slick-greeter#143]
```
slick-greeter version: 1.2.7
Distribution - Manjaro Budgie
Graphics hardware *and* driver used
Intel® Haswell Mobile, 64 bit Surface Pro 3
 ```

**Issue**

On the Budgie Desktop log in screen, when using a high DPI display, like the one on the Surface Pro, the input field for the password, as well as the icons in the top panel are unnaturally small. On typical full-HD monitors the password input window is simply usually much bigger.

After log in, everything scales-up properly though, once the display auto-scales from 100 to 200%.

**Steps to reproduce**
Use a distribution of Manjaro, or Ubuntu Budgie, since that uses slick-greeter.

**Expected behaviour**
The log in interface should scale properly even on the log in screen (that is not to 100, but 200% when a resolution like 2160x1440 is detected on boot.

**Other information**

**Comment by JosephMcc** [comment]
It does check for HiDPI and scale properly in most cases. The problem is that 1440p is a bit tricky. This is a common resolution in many larger monitors that should not be scaled 2x. There is some limitation on how reliable the info we get from hardware is for determining HiDPI by another method. You can set the value for this to 2x yourself in the settings for the login window in case you don't know.
