### ISSUE TITLE
Previous session checking should use [LightDM].sessions-directory setting

### ISSUE THREAD

**Issue by Psykar** [linuxmint/slick-greeter#150]
**Issue**
Currently when validating the previous session it checks against a hardcoded path: `/usr/share/xsessions/`
https://github.com/linuxmint/slick-greeter/blob/master/src/slick-greeter.vala#L200

This should instead look at the value in lightdm's settings
```
[LightDM]
sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions
```

Without this, the previous session is selected only if it was in xsessions, so wayland sessions (for example) will never appear to be saved.

I can't immediately see how to access lightdm's settings in code without loading the file from scratch (which doesn't seem correct) or I would have just opened a PR!

**Comment by Psykar** [comment]
Any objections to having `validate_session` check the given session string against the above three directories being hardcoded?
ie:
```
/usr/share/lightdm/sessions
/usr/share/xsessions
/usr/share/wayland-sessions
```

**Comment by leigh123linux** [comment]
I object to /usr/share/lightdm/sessions , no distro's should use that.
The wayland is ok but pointless IMO as it has never worked here to launch any wayland sessions.

**Comment by Psykar** [comment]
@leigh123linux *shrug
Tell the lightdm developers themselves then I guess - it's the default setting for this:
https://github.com/canonical/lightdm/blob/03f218981733e50d810767f9d04e42ee156f7feb/src/Makefile.am#L84

I'm still confused why you think slick-greeter can't launch wayland sessions, when it clearly can as I use it daily. I've made no customizations to lightdm except changing the greeter (obviously)

My preference would be to load it from `lightdm.conf` but after digging it seems lightdm doesn't expose this setting on it's API to greeters, and manually parsing the config file seems like it would be a slippery slope.

Next preference would be a config variable for the greeter (although does result in repitition - but we can have it default to 
```
/usr/share/lightdm/sessions
/usr/share/xsessions
/usr/share/wayland-sessions
```  - or leave out lightdm/sessions if we're that against it )

**Comment by dron1885** [comment]
Following dirty hack in `validate_session` from slick-greeter.vala  (around line 215 ) works with previous Plasama-wayland and Sway sessions. 
```
var path = Path.build_filename  ("/usr/share/xsessions/", session.concat(".desktop"), null);
var waypath = Path.build_filename  ("/usr/share/wayland-sessions", session.concat(".desktop"), null);
            
 if (!FileUtils.test (path, FileTest.EXISTS) & !FileUtils.test (waypath, FileTest.EXISTS)) {
```
I don't think that proper implementation for wayland sessions here and in `get_default_session` would hurt.

**Comment by major-mayer** [comment]
I'm having the same problem here. 
I've renamed my gnome.desktop file in xsessions, so that I don't get this duplicate key error as described [here](https://wiki.archlinux.org/index.php/LightDM#Wayland_session_not_working_with_duplicate_GNOME_entries_in_greeter).
The directories now look like this:
```zsh
~ >>> ls -l /usr/share/wayland-sessions /usr/share/xsessions                   
/usr/share/wayland-sessions:
insgesamt 8
-rw-r--r-- 1 root root 7829 29. Dez 19:14 gnome.desktop

/usr/share/xsessions:
insgesamt 28
-rw-r--r-- 1 root root 7874  3. Dez 01:32 gnome-classic.desktop
-rw-r--r-- 1 root root 7829 29. Dez 19:14 gnome.desktop.disabled
-rw-r--r-- 1 root root 7914 29. Dez 19:14 gnome-xorg.desktop
-rw-r--r-- 1 root root  138 17. Dez 12:41 kodi.desktop
``` 

In my lightdm configuration file I only changed `user-session=gnome` and `greeter-session=lightdm-slick-greeter`.
The interesting and confusing result now is, that LightDM always uses the Gnome Xorg session automatically, but when you click on this small icon to change the session type it says "Gnome - default".
This sounds great, because "Gnome" without any postfix ist the Wayland session and if it would be really the default one I would be more than happy.
But instead it always logs me into the X11 session if I don't manually change the session type to "Gnome - default".
