### ISSUE TITLE
hidpi: Fractional Scaling (125% or 150%) not available

### ISSUE THREAD

**Issue by Darthpenguin** [linuxmint/slick-greeter#202]
```
 * slick-greeter 1.5.7
 * Arch Linux
 * 00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
 * 64 bit
 ```

**Issue**
This might just be a feature request. Sorry if this is the wrong place to post this.
HiDPI can be on or off or auto but there is no option for fractional scaling. For example to scale to 125% or 150%

**Steps to reproduce**
Install and setup the slick-greeter and it's companion lightdm-settings application. There is no option to scale to 125% or 150%

**Expected behaviour**
Would love to have an option to set the HiDPI to 125% so it matches the cinnamon display configuration

**Other information**
That's all. :)

**Comment by NoRefill** [comment]
I think this is the same issue I have. I have an RX6800 using amdgpu driver and fractional scaling of 125% on 4k monitor. Once I'm logged in, things seem to work fine (other than the screensaver changing resolutions but that seems to be fixed by a different patch packages), but the greeter starts the X server at 1080p and some windows that start up are not where the should be and other windows are "squished" because the resolution is not at the scaled 4k. I have tried a million different things like setting the resolution using xrandr scripts during greeter startup and such things and none of them work even though the scripts all have run and return 0. I'm on Linux Mint 21 using slick-greeter 1.5.9.

**Comment by clefebvre** [comment]
Fractional scaling isn't planned.

That said, you should be able to turn HiDPI OFF and set the resolution you want via an xrandr script. Can you show more information about the script you're running, and you're configuring it?

**Comment by clefebvre** [comment]
Also provide the output of `xrandr` and `sudo get-edid | parse-edid`.

**Comment by NoRefill** [comment]
> 

I disabled HiDPI and the greeter now comes up in 4K without the need of using an xrandr script. I still have a application window that is started on login that is position like the resolution is 1080p instead of 4K and I see the monitor blank like it is changing resolutions between greeter and getting to the desktop. I'm not sure it has anything to do with the the greeter at this point though. Thanks for the suggestions.

**Comment by clefebvre** [comment]
No pb, I'll close this for now. Please reopen a new issue if needed.
