### ISSUE TITLE
draw-user-background completely ignored

### ISSUE THREAD

**Issue by kanehekili** [linuxmint/slick-greeter#213]
```
 * slick-greeter version 1.5.4
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used
 * >NIVIDIA GT218M Version 340.108
 *  64 bit
 ```

**Issue**
draw-user-background does not only not work, it prevents any other backgrounds to be shown

**Steps to reproduce**
add any image to the /etc/lightdm/slickgreeter,conf and set "draw-user-background =true". Your code will guarantee that the -permanently overwritten - lunixmint.jpg file from the /var/lib/Accountservice/user/<username> file will be displayed.

**Expected behavior**
I'd expect that the user background image is displayed, not some Linuxmint logo. 

**Other information**
The accountservice file mentioned above is overwritten,  a chattr +i <username> could prevent overwriting, but not the display of the "default" background image.
That "draw-user-background" flag does not work with the "lightdm-gtk-greeter" as well. >>WTF

**Comment by clefebvre** [comment]
Fixed in later version. Can't be reproduced in Mint 21.1 with slick-greeter 1.5.9.

![VirtualBox_SSD_25_01_2023_11_10_10](https://user-images.githubusercontent.com/1138515/214548748-1f3e9548-6495-4ed9-8e04-2add91a375fb.png)

![Capture d’écran du 2023-01-25 11-10-44](https://user-images.githubusercontent.com/1138515/214548763-8b66cfff-73de-449b-9015-a322ea577f72.png)

Note in case it's a user error: If your background is pointing to a file which is not readable by other users (encrypted home dir, or restricted permissions on your home dir) it can't be displayed.

**Comment by kanehekili** [comment]
Thanks. Only difference is, that it doesn't seem to work in XFCE (which i forgot to mention). Test with Cinnamon 20 worked btw.

**Comment by clefebvre** [comment]
Ah that could be a bug on Xfce then.. make sure changing the background in Xfce results in the filename being set in /var/lib/AccountsService/user/<yourusername>. You might need to be root to access this location.
