### ISSUE TITLE
[Feature Request] Implement lock-screen/screensaver

### ISSUE THREAD

**Issue by Ste74** [linuxmint/slick-greeter#68]
Hi there , us ( Manjaro Linux ) and i think also @ikeydoherty ( Solus ) and @fossfreedom ( Ubuntu Budgie ) are interested at the screensaver implementation in order to drop the gnome legacy screensaver .. ( guys correct me if i wrong :p and sorry if mention you :p ) . In the source code i don't see this .. any plan to add this feature ?

Stefano Capitani
Manjaro Team

**Comment by ikeydoherty** [comment]
I might be wrong but I think thats handled through light-locker?

**Comment by fossfreedom** [comment]
I thought light-locker had ceased ... but I noticed a few commits lately.  So still alive?  I couldnt get it to work the last time I looked at it though (12+ months ago)

**Comment by ikeydoherty** [comment]
I just had a play with it, and it refuses to run because of GSD's ScreensaverProxy, which can only be turned off with hacks (redirected .desktop files ...)

Hate to say it lads but we might just have to fork gnome-screensaver.

**Comment by mtwebster** [comment]
I don't care one way or the other but we ported our old fork of gnome-screensaver to (mostly) python a while back, if you want yet another option to fork.. it doesn't use lightdm but it could be simpler to start with.  Other than the name it's more or less DE-independent for now (though I have never tried it in a session where gsd was running).

**Comment by Ste74** [comment]
Hi , what do you mean with old fork , light-locker?

**Comment by ikeydoherty** [comment]
I believe @mtwebster is talking about cinnamon screensaver. I remember reading about that, where it was claimed that porting it to Python made it faster than C - which you know I'm never going to buy. It's also not pure C if I recollect correctly, but it took the bulk of gnome-screensaver and converted it to an in-tree C library..

**Comment by JosephMcc** [comment]
Not sure who made the claim that porting to Python made it faster somehow. In the case of the screensaver I'm not sure speed is really a large issue though.

**Comment by ikeydoherty** [comment]
@JosephMcc you saying the Linux world has unreliable news coverage? :P

**Comment by JosephMcc** [comment]
What!? No way... ;)

**Comment by mtwebster** [comment]
The vast majority of it is in python, the remaining C is either autogenerated gdbus-codegen files for various services, or things that couldn't reliably be performed in python, either due to lack of python3 support for xlib on some distros, or GdkScreen behavior being at odds with the wm, among other things.  The pam authentication stuff was also re-used (lightdm wasn't on our radar yet at that time.)

The main reason we did it was to get rid of growing problems like GtkPlug/GtkSocket rot and to make it a bit more accessible for maintenance and development.  I wasn't trying to peddle our own wares here, I was just offering up an alternative to start with - I have no doubt you'd likely want to rip the entire ui out, but the plumbing is in, it connects to the proper things, etc...

**Comment by ikeydoherty** [comment]
IDK the UI looks alright to me - and I whole heartedly agree with axing the GtkPlug/GtkSocket nonsense.

**Comment by Ste74** [comment]
So is possible do a cinnamon-screensaver Distro/DE agnostic? @ikeydoherty know me i'm not a programmer :p

**Comment by wfio** [comment]
Not to be a jerk but it looks like the OP's question was never answered or resolved as you guys spun off into a who's right/wrong on C vs Python. I've just started using slick-greeter and it's awesome but the experience is really dragged down when Debian goes to lock screen and we're back to using the gnome default lock screen login prompt.

**Comment by alichtman** [comment]
I'll try `slick-greeter` again if this issue gets fixed.

**Comment by clefebvre** [comment]
Slick greeter is a lightdm greeter. Light-locker can lock your session and show your lightdm prompt instead of a screensaver. This has limitations though, you're no longer active on your session seat if that makes sense.. for instance you no longer have access to sound. I wouldn't recommend it if the DE has a decent screensaver.
