### ISSUE TITLE
Wrong login screen resolution with external monitor.

### ISSUE THREAD

**Issue by HoracioDos** [linuxmint/slick-greeter#70]
Package: slick-greeter Version: 1.0.7+sonya
System: Host: U47VC Kernel: 4.4.0-91-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.6 Distro: Linux Mint 18.2 Sonya
Graphics: Card-1: Intel 3rd Gen Core processor Graphics Controller Card-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] Display Server: X.Org 1.18.4 driver: nvidia Resolution: 1366x768@60.00hz, 1920x1080@60.00hz GLX Renderer: GeForce GT 620M/PCIe/SSE2 GLX Version: 4.4.0 NVIDIA 340.102

**Issue**
Login screen resolution is smaller than monitor resolution. External monitor is always set as primary display
Picture attached.

**Steps to reproduce**
Connect an external monitor and login.

**Expected behaviour**
Login screen resolution should have monitor resolution. MDM works fine.

**Other information**
/var/log/lightdm/seat0-greeter.log
![login screen on external monitor](https://user-images.githubusercontent.com/4549674/29235085-3223e792-7ed2-11e7-9bc3-b994b277384a.jpg)
[seat0-greeter.log.txt](https://github.com/linuxmint/slick-greeter/files/1219282/seat0-greeter.log.txt)

 attached

**Comment by besser82** [comment]
From the attached log it looks like you have mirrored monitors setup in the kernel command line, thus slick-greeter (or better said the XServer) treats them like one.  Since mirrored monitors *always* need to use the smallest common resolution, the screen is rendered at 1366 x 768…

**Comment by HoracioDos** [comment]
Hello!
Could you please explain a little more "mirrored monitors setup in the kernel command line"? I created a file called 10-monitor.conf in /etc/X11/xorg.conf.d 
`Section "Monitor"
    Identifier  "LVDS1"
    Option      "Primary" "true"
EndSection

Section "Monitor"
    Identifier  "HDMI1"
    Option      "RightOf" "LVDS1"
EndSection`
It's working now but is it the correct way to do it?
Thanks!!

**Comment by besser82** [comment]
`Could you please explain a little more "mirrored monitors setup in the kernel command line"?`

Well, for some reason the screens get mirrored instead of positioned next to each other…  That can be for different reasons; either setting up a special command in grub that's passed to the kernel or caused by the graphics driver itself…

**Comment by ariefcfa** [comment]
Hi,

I encountered the same issue (wrong screen resolution on login window) but in my case, it wrong on system wide. I manage to fixed it by following a tutorial from https://askubuntu.com/questions/73804/wrong-login-screen-resolution and correcting my display settings (i was mirrored at first).

But, one issue remains. The top panel is not expanded to full screen width (please see attached screenshot). The same issue happened for background image.

Where can i tweak the top panel and the background to make it fit my screen width?

Thanks in advance.
Regards
![ask-linuxmint-loginwindow -small](https://user-images.githubusercontent.com/34770799/34298460-8eccc45a-e750-11e7-8f4e-5f07ac2e2f8a.jpg)

**Comment by ariefcfa** [comment]
Hi, i just solved my issue by replicating solution posted by HoracioDos [https://github.com/linuxmint/slick-greeter/issues/70#issuecomment-347702111](url). But for me, i don't use external monitor. I tested to take screenshot on Login Windows and it appear the screenshot is as if i use two monitor (my laptop screen and external vga monitor). No problem, because on desktop inactive. 

I guess the issue is with my graphic driver or kernel, not with Slick Greeter. And for it the fix should applied on that parts. Sorry for my English. Cheers

**Comment by Vahan86** [comment]
@HoracioDos, is this still an issue for you with slick-greeter 1.3.2 (Linux Mint 19.3, Cinnamon 4.4)?
