### ISSUE TITLE
Session language selector support

### ISSUE THREAD

**Issue by geotom** [linuxmint/slick-greeter#77]
```
 * slick-greeter version 1.0.7
 * Distribution - Mint 18.2
 * Graphics hardware NVIDIA
 * 64 bit
 ```

I wonder if there is any support for choosing a session language. So far I couldn't find it and the lightdm-gtk-setting "show-language-selector=true also had no effect. I guess it is just not supported!? Any plans to add this as I think it's quite useful and needed for multi language support in mixed language environments (work/private)

**Comment by Richy91** [comment]
It would be nice if you could choose keyboard in greeter.  For example if you add keyboard in session it would add in greeter as well. Now, for example, if you add russian keyboard and change password in russian, then you are locked out of computer, because you can't change keyboard in greeter.

**Comment by valholl** [comment]
I'm using version 1.2.2 of slick-greeter, and this does not seem to be available.

Such a feature would be extremely useful in shared computers (e.g. school labs or libraries) where users have different native languages.

IIUC other greeters make this change by writing a line `Language=<language_code>` in `~/.dmrc`

**Comment by paolodongilli** [comment]
As @valholl writes, this feature is fundamental for many schools of our region (South Tyrol). We decided to adopt `slick-greeter` (on Debian with Xfce and LightDM) because the default `lightdm-gtk-greeter`isn't able to correctly show all messages to the user during login/password change.
We have now 4.000 PCs installing `slick-greeter` and 16.000 students + 1.800 teacher will start using it at the beginning of September.

**Comment by brunosoli** [comment]
I know it's a kinda old thread and off-topic but, @paolodongilli did you get slick-greeter to correctly display messages in other languages during password changing?
We got lightdm and slick-greeter (on Mint 19.2 Mate) running in pt_BR. Everything works fine, except for these messages.

**Comment by Vahan86** [comment]
Still an issue in Linux Mint 19.3, Cinnamon 4.4, slick-greeter 1.3.2.

**Comment by brunosoli** [comment]
Still an issue in Linux Mint 19.3, Mate 1.22.2, slick-greeter 1.3.2.
How is it related to issue #142?

**Comment by moriel5** [comment]
I have a similar, if not the same issue. And please correct me if this is a different component.

When session is locked, I have no way of changing the keyboard language, so if I carelessly leave the language to anything other than English when the session is locked, I have no way of unlocking the session, since I use a completely different script that does not rely on Latin characters at all.

At the moment, my only recourse is to kill the LightDM process, losing anything that was open in the process, and login normally.

**Comment by clefebvre** [comment]
The session language is something that is configured and chosen in the session itself (by a tool like mintlocale or similar). This is by design. We don't support overriding this from the greeter.

The keyboard layout selection was added recently: https://github.com/linuxmint/slick-greeter/commit/1aa6d5888df372c677cbc06a770e7ab2e4f0c8b6.
