### ISSUE TITLE
Feature Request: Clickable Login Button?

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/slick-greeter#87]
```
 * slick-greeter version: slick-greeter 1.0.8
 * Distribution - Ubuntu 18.04
 ```

**Feature Request**
Personally I don't have an issue, but many novice users don't understand how to login after typing in their password, as there is no "arrow" at the right of the password box like unity-greeter used to have.  So for usability I think it would be good to have some indication of what to click for a user (yes yes, I use "Enter" key and don't need it, but again several of our users have been confused)

**Comment by LinuxOnTheDesktop** [comment]
I don't know why this hasn't been fixed. (I presume it is not fixed in Mint 19.3) After all, fixing it would make the distribution more user-friendly and would so, it seems to me, at the cost, only, of a small amount of developer time.

**Comment by icarter09** [comment]
Mint 19.3
slick-greeter 1.3.1

There is an arrow icon in the password box. Is that icon not user friendly?

**Comment by LinuxOnTheDesktop** [comment]
I see that now - as of Mint 19.3? - an arrow appears in the password box, once one starts to type in that box. I find also that the icon is clickable. I had been assuming, I think, that since this bug report was open, there was no arrow (/login button) or at least no clickable arrow.

So, unless I miss something, this issue can be closed.

**Comment by icarter09** [comment]
@LinuxOnTheDesktop no worries and thanks for the update. If we feel the login feature isn't intuitive enough for a new user, then we can reopen this issue or create a new one.
